name: "S3 Cache for GitHub Actions"
description: "GitHub Action that allows you to cache build artifacts to S3"
branding:
  icon: "archive"
  color: "green"
inputs:
  action:
    description: "Action to perform. Options are: put, get, delete"
    required: true
  aws-access-key-id:
    description: "AWS access key id to access your bucket"
    required: true
  aws-secret-access-key:
    description: "AWS secret access key to access your bucket"
    required: true
  aws-region:
    description: "AWS region where your bucket is located"
    required: true
  bucket:
    description: "AWS s3 bucket to store the artifacts"
    required: true
  key:
    description: "An explicit key for restoring and saving the cache"
    required: true
  artifacts:
    description: "A list of files, directories and glob patterns to cache and restore"
    required: false
runs:
  using: "composite"
  steps:
    - run: ./entrypoint.sh
      shell: bash
      env:
        ACTION: ${{ inputs.action }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_REGION: ${{ inputs.aws-region }}
        BUCKET: ${{ inputs.bucket }}
        KEY: ${{ inputs.key }}
        ARTIFACTS: ${{ inputs.artifacts }}
        OS: ${{ runner.os }}
