name: "s3 Cache artifacts"
description: "Send artifacts to s3 to improve build time"
runs:
  using: "composite"
  steps:
    - run: ./entrypoint.sh
      shell: bash
      env:
        ACTION: ${{ inputs.action }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        BUCKET: ${{ inputs.bucket }}
        KEY: ${{ inputs.key }}
        ARTIFACTS: ${{ inputs.artifacts }}
        OS: ${{ runner.os }}
