name: Test
on:
  - push

jobs:
  test_on_machine:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11.0, windows-2019]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.15.5"
      - name: Export vars
        id: vars
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == ubuntu-* ]]; then
            echo "::set-output name=GOOS::linux"
          elif [[ "${{ matrix.os }}" == macos-* ]]; then
            echo "::set-output name=GOOS::darwin"
          else
            echo "::set-output name=GOOS::windows"
          fi
      - name: Build binary
        env:
          GOARCH: "amd64"
          GOOS: ${{ steps.vars.outputs.GOOS }}
        run: go build -o dist/$(echo "${{ runner.os }}" | tr "[:upper:]" "[:lower:]")
        shell: bash

      - name: Create temp files
        shell: bash
        run: |
          mkdir -p temp/{dir1,dir2,dir3}/{subdir1,subdir2,subdir3}
          echo "fileexample" > temp/file.txt
          cat temp/file.txt | tee temp/dir1/file.txt temp/dir2/file.txt temp/dir3/file.txt temp/dir1/subdir1/file.txt temp/dir2/subdir2/file.txt temp/dir3/subdir3/file.txt

      - uses: ./
        with:
          action: put
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          bucket: ${{ secrets.AWS_BUCKET }}
          key: ${{ hashFiles('action.yml') }}-${{ matrix.os }}
          artifacts: |
            node_modules/**
            batata
            .batatarc
